######################################################################
##
## Filename: AFE_Fpga_A_tb.udo
## Created on: Mon Jul 22 1:59:57 PM Central Daylight Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
