######################################################################
##
## Filename: AFE_Fpga_A_tb.udo
## Created on: Tue Jul 12 07:11:32 PM EDT 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
