onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /afe_fpga_a_tb/ClkB_P
add wave -noupdate /afe_fpga_a_tb/ClkB_N
add wave -noupdate /afe_fpga_a_tb/VXO_P
add wave -noupdate /afe_fpga_a_tb/VXO_N
add wave -noupdate /afe_fpga_a_tb/CpldRst
add wave -noupdate /afe_fpga_a_tb/CpldCS
add wave -noupdate /afe_fpga_a_tb/uCRd
add wave -noupdate /afe_fpga_a_tb/uCWr
add wave -noupdate /afe_fpga_a_tb/uCA
add wave -noupdate /afe_fpga_a_tb/GA
add wave -noupdate /afe_fpga_a_tb/AFESDO
add wave -noupdate /afe_fpga_a_tb/AFEDCO_P
add wave -noupdate /afe_fpga_a_tb/AFEDCO_N
add wave -noupdate /afe_fpga_a_tb/AFEFR_P
add wave -noupdate /afe_fpga_a_tb/AFEFR_N
add wave -noupdate /afe_fpga_a_tb/AFEDat0_P
add wave -noupdate /afe_fpga_a_tb/AFEDat0_N
add wave -noupdate /afe_fpga_a_tb/AFEDat1_P
add wave -noupdate /afe_fpga_a_tb/AFEDat1_N
add wave -noupdate /afe_fpga_a_tb/GPI1
add wave -noupdate /afe_fpga_a_tb/GPI0_N
add wave -noupdate /afe_fpga_a_tb/GPI0_P
add wave -noupdate /afe_fpga_a_tb/A7
add wave -noupdate /afe_fpga_a_tb/R10
add wave -noupdate /afe_fpga_a_tb/N8
add wave -noupdate /afe_fpga_a_tb/uCD
add wave -noupdate /afe_fpga_a_tb/SDD
add wave -noupdate /afe_fpga_a_tb/UDQS
add wave -noupdate /afe_fpga_a_tb/LDQS
add wave -noupdate /afe_fpga_a_tb/SDRzq
add wave -noupdate /afe_fpga_a_tb/Temp
add wave -noupdate /afe_fpga_a_tb/SDCKE
add wave -noupdate /afe_fpga_a_tb/LDM
add wave -noupdate /afe_fpga_a_tb/UDM
add wave -noupdate /afe_fpga_a_tb/RAS
add wave -noupdate /afe_fpga_a_tb/CAS
add wave -noupdate /afe_fpga_a_tb/SDWE
add wave -noupdate /afe_fpga_a_tb/SDClk_P
add wave -noupdate /afe_fpga_a_tb/SDClk_N
add wave -noupdate /afe_fpga_a_tb/SDA
add wave -noupdate /afe_fpga_a_tb/BA
add wave -noupdate /afe_fpga_a_tb/AFEPDn
add wave -noupdate /afe_fpga_a_tb/AFECS
add wave -noupdate /afe_fpga_a_tb/AFEClk_P
add wave -noupdate /afe_fpga_a_tb/AFEClk_N
add wave -noupdate /afe_fpga_a_tb/AFESClk
add wave -noupdate /afe_fpga_a_tb/AFESDI
add wave -noupdate /afe_fpga_a_tb/AFERst
add wave -noupdate /afe_fpga_a_tb/MuxEn
add wave -noupdate /afe_fpga_a_tb/Muxad
add wave -noupdate /afe_fpga_a_tb/Pulse
add wave -noupdate /afe_fpga_a_tb/PulseSel
add wave -noupdate /afe_fpga_a_tb/DACCS
add wave -noupdate /afe_fpga_a_tb/DACClk
add wave -noupdate /afe_fpga_a_tb/DACDat
add wave -noupdate /afe_fpga_a_tb/DACLd
add wave -noupdate /afe_fpga_a_tb/Debug
add wave -noupdate /afe_fpga_a_tb/TxReg0
add wave -noupdate /afe_fpga_a_tb/TxReg1
add wave -noupdate /afe_fpga_a_tb/DDR_Tap0
add wave -noupdate /afe_fpga_a_tb/DDR_Tap1
add wave -noupdate /afe_fpga_a_tb/DDR_LSFR0
add wave -noupdate /afe_fpga_a_tb/DDR_LSFR1
add wave -noupdate /afe_fpga_a_tb/iAFEFR
add wave -noupdate /afe_fpga_a_tb/AFEDCODL
add wave -noupdate /afe_fpga_a_tb/Gap_Count
add wave -noupdate /afe_fpga_a_tb/IntDQSClk
add wave -noupdate /afe_fpga_a_tb/iDQS
add wave -noupdate /afe_fpga_a_tb/BurstCount
add wave -noupdate /afe_fpga_a_tb/DDR_LSFR
add wave -noupdate /afe_fpga_a_tb/DDR_Tap
add wave -noupdate /afe_fpga_a_tb/DDR_Rx_State
add wave -noupdate /afe_fpga_a_tb/BitCount
add wave -noupdate /afe_fpga_a_tb/PULSECNT
add wave -noupdate /afe_fpga_a_tb/COUNT
add wave -noupdate /afe_fpga_a_tb/RdReg
add wave -noupdate /afe_fpga_a_tb/FMWord
add wave -noupdate /afe_fpga_a_tb/PresentAD
add wave -noupdate /afe_fpga_a_tb/ResetHi
add wave -noupdate /afe_fpga_a_tb/TxEn
add wave -noupdate /afe_fpga_a_tb/Clk53
add wave -noupdate /afe_fpga_a_tb/TxReq
add wave -noupdate /afe_fpga_a_tb/TxAck
add wave -noupdate /afe_fpga_a_tb/uBunchWidth
add wave -noupdate /afe_fpga_a_tb/Tx1_Out
add wave -noupdate /afe_fpga_a_tb/Tx_State
add wave -noupdate /afe_fpga_a_tb/FM_Index
add wave -noupdate /afe_fpga_a_tb/uut/SDwr_en
add wave -noupdate /afe_fpga_a_tb/uut/SDwr_full
add wave -noupdate /afe_fpga_a_tb/uut/SDwr_empty
add wave -noupdate /afe_fpga_a_tb/uut/SDwr_error
add wave -noupdate /afe_fpga_a_tb/uut/SDwr_underrun
add wave -noupdate /afe_fpga_a_tb/uut/SDwr_count
add wave -noupdate /afe_fpga_a_tb/uut/DDR_Write_Seq
add wave -noupdate /afe_fpga_a_tb/uut/GateReq
add wave -noupdate /afe_fpga_a_tb/uut/ADCSmplGate
add wave -noupdate /afe_fpga_a_tb/uut/ADCSmplCntr
add wave -noupdate /afe_fpga_a_tb/uut/ADCSmplCntReg
add wave -noupdate /afe_fpga_a_tb/uut/EvBuffWrt
add wave -noupdate /afe_fpga_a_tb/uut/EvBuffRd
add wave -noupdate /afe_fpga_a_tb/uut/EvBuffEmpty
add wave -noupdate /afe_fpga_a_tb/uut/EvBuffFull
add wave -noupdate /afe_fpga_a_tb/uut/SlfTrgEdge
add wave -noupdate /afe_fpga_a_tb/uut/EvBuffDat
add wave -noupdate /afe_fpga_a_tb/uut/EvBufffOut
add wave -noupdate /afe_fpga_a_tb/uut/Outs
add wave -noupdate /afe_fpga_a_tb/uut/EvBuffWdsUsed
add wave -noupdate /afe_fpga_a_tb/PULSECNT
add wave -noupdate /afe_fpga_a_tb/COUNT
add wave -noupdate /afe_fpga_a_tb/TxReg0
add wave -noupdate -expand -subitemconfig {/afe_fpga_a_tb/uut/FrDat(0) -expand} /afe_fpga_a_tb/uut/FrDat
add wave -noupdate /afe_fpga_a_tb/uut/SlipReq
add wave -noupdate /afe_fpga_a_tb/iAFEFR
add wave -noupdate /afe_fpga_a_tb/AFEFR_P
add wave -noupdate /afe_fpga_a_tb/uut/Ins
add wave -noupdate /afe_fpga_a_tb/uut/OutsFront
add wave -noupdate /afe_fpga_a_tb/ClkB_P
add wave -noupdate /afe_fpga_a_tb/ClkB_N
add wave -noupdate /afe_fpga_a_tb/VXO_P
add wave -noupdate /afe_fpga_a_tb/VXO_N
add wave -noupdate /afe_fpga_a_tb/CpldRst
add wave -noupdate /afe_fpga_a_tb/CpldCS
add wave -noupdate /afe_fpga_a_tb/uCRd
add wave -noupdate /afe_fpga_a_tb/uCWr
add wave -noupdate /afe_fpga_a_tb/uCA
add wave -noupdate /afe_fpga_a_tb/GA
add wave -noupdate /afe_fpga_a_tb/AFESDO
add wave -noupdate /afe_fpga_a_tb/AFEDCO_P
add wave -noupdate /afe_fpga_a_tb/AFEDCO_N
add wave -noupdate /afe_fpga_a_tb/AFEFR_P
add wave -noupdate /afe_fpga_a_tb/AFEFR_N
add wave -noupdate /afe_fpga_a_tb/AFEDat0_P
add wave -noupdate /afe_fpga_a_tb/AFEDat0_N
add wave -noupdate /afe_fpga_a_tb/AFEDat1_P
add wave -noupdate /afe_fpga_a_tb/AFEDat1_N
add wave -noupdate /afe_fpga_a_tb/GPI1
add wave -noupdate /afe_fpga_a_tb/GPI0_N
add wave -noupdate /afe_fpga_a_tb/GPI0_P
add wave -noupdate /afe_fpga_a_tb/A7
add wave -noupdate /afe_fpga_a_tb/R10
add wave -noupdate /afe_fpga_a_tb/N8
add wave -noupdate /afe_fpga_a_tb/uCD
add wave -noupdate /afe_fpga_a_tb/SDD
add wave -noupdate /afe_fpga_a_tb/UDQS
add wave -noupdate /afe_fpga_a_tb/LDQS
add wave -noupdate /afe_fpga_a_tb/SDRzq
add wave -noupdate /afe_fpga_a_tb/Temp
add wave -noupdate /afe_fpga_a_tb/SDCKE
add wave -noupdate /afe_fpga_a_tb/LDM
add wave -noupdate /afe_fpga_a_tb/UDM
add wave -noupdate /afe_fpga_a_tb/RAS
add wave -noupdate /afe_fpga_a_tb/CAS
add wave -noupdate /afe_fpga_a_tb/SDWE
add wave -noupdate /afe_fpga_a_tb/SDClk_P
add wave -noupdate /afe_fpga_a_tb/SDClk_N
add wave -noupdate /afe_fpga_a_tb/SDA
add wave -noupdate /afe_fpga_a_tb/BA
add wave -noupdate /afe_fpga_a_tb/AFEPDn
add wave -noupdate /afe_fpga_a_tb/AFECS
add wave -noupdate /afe_fpga_a_tb/AFEClk_P
add wave -noupdate /afe_fpga_a_tb/AFEClk_N
add wave -noupdate /afe_fpga_a_tb/AFESClk
add wave -noupdate /afe_fpga_a_tb/AFESDI
add wave -noupdate /afe_fpga_a_tb/AFERst
add wave -noupdate /afe_fpga_a_tb/MuxEn
add wave -noupdate /afe_fpga_a_tb/Muxad
add wave -noupdate /afe_fpga_a_tb/Pulse
add wave -noupdate /afe_fpga_a_tb/PulseSel
add wave -noupdate /afe_fpga_a_tb/DACCS
add wave -noupdate /afe_fpga_a_tb/DACClk
add wave -noupdate /afe_fpga_a_tb/DACDat
add wave -noupdate /afe_fpga_a_tb/DACLd
add wave -noupdate /afe_fpga_a_tb/Debug
add wave -noupdate /afe_fpga_a_tb/TxReg0
add wave -noupdate /afe_fpga_a_tb/TxReg1
add wave -noupdate /afe_fpga_a_tb/DDR_Tap0
add wave -noupdate /afe_fpga_a_tb/DDR_Tap1
add wave -noupdate /afe_fpga_a_tb/DDR_LSFR0
add wave -noupdate /afe_fpga_a_tb/DDR_LSFR1
add wave -noupdate /afe_fpga_a_tb/iAFEFR
add wave -noupdate /afe_fpga_a_tb/AFEDCODL
add wave -noupdate /afe_fpga_a_tb/Gap_Count
add wave -noupdate /afe_fpga_a_tb/IntDQSClk
add wave -noupdate /afe_fpga_a_tb/iDQS
add wave -noupdate /afe_fpga_a_tb/BurstCount
add wave -noupdate /afe_fpga_a_tb/DDR_LSFR
add wave -noupdate /afe_fpga_a_tb/DDR_Tap
add wave -noupdate /afe_fpga_a_tb/DDR_Rx_State
add wave -noupdate /afe_fpga_a_tb/BitCount
add wave -noupdate /afe_fpga_a_tb/PULSECNT
add wave -noupdate /afe_fpga_a_tb/COUNT
add wave -noupdate /afe_fpga_a_tb/RdReg
add wave -noupdate /afe_fpga_a_tb/FMWord
add wave -noupdate /afe_fpga_a_tb/PresentAD
add wave -noupdate /afe_fpga_a_tb/ResetHi
add wave -noupdate /afe_fpga_a_tb/TxEn
add wave -noupdate /afe_fpga_a_tb/Clk53
add wave -noupdate /afe_fpga_a_tb/TxReq
add wave -noupdate /afe_fpga_a_tb/TxAck
add wave -noupdate /afe_fpga_a_tb/uBunchWidth
add wave -noupdate /afe_fpga_a_tb/Tx1_Out
add wave -noupdate /afe_fpga_a_tb/Tx_State
add wave -noupdate /afe_fpga_a_tb/FM_Index
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2243565 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 203
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {1312500 ps}
